apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: { name: ott-basics, namespace: ott-platform }
spec:
  groups:
  - name: availability
    rules:
    - alert: ServiceDown
      expr: up == 0
      for: 1m
      labels: { severity: critical }
      annotations: { summary: "Service down", description: "Target sin scrape por 1m" }
