apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: api-auth-monitor, namespace: ott-platform }
spec:
  selector: { matchLabels: { app: auth-api } }
  endpoints: [ { port: http, path: /health, interval: 15s } ]
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: cdn-monitor, namespace: ott-platform }
spec:
  selector: { matchLabels: { app: cdn-edge } }
  endpoints: [ { port: http, path: /metrics, interval: 10s } ]
