apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: subscription-monitor, namespace: ott-platform }
spec: { selector: { matchLabels: { app: subscription-api } }, endpoints: [ { port: http, path: /metrics, interval: 15s } ] }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: catalog-monitor, namespace: ott-platform }
spec: { selector: { matchLabels: { app: catalog-api } }, endpoints: [ { port: http, path: /metrics, interval: 15s } ] }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: license-monitor, namespace: ott-platform }
spec: { selector: { matchLabels: { app: license-api } }, endpoints: [ { port: http, path: /metrics, interval: 15s } ] }
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata: { name: cas-monitor, namespace: ott-platform }
spec: { selector: { matchLabels: { app: cas-api } }, endpoints: [ { port: http, path: /metrics, interval: 15s } ] }
