apiVersion: apps/v1
kind: Deployment
metadata: { name: license-api-deployment, namespace: ott-platform, labels: { app: license-api } }
spec:
  replicas: 1
  selector: { matchLabels: { app: license-api } }
  template:
    metadata: { labels: { app: license-api } }
    spec:
      containers:
      - name: license
        image: python:3.11-slim
        command: ["python","/app/app.py"]
        ports: [ { containerPort: 5003 } ]
        volumeMounts: [ { name: code, mountPath: /app } ]
      volumes: [ { name: code, configMap: { name: license-api-code } } ]
---
apiVersion: v1
kind: Service
metadata: { name: license-api-service, namespace: ott-platform }
spec:
  selector: { app: license-api }
  ports: [ { name: http, port: 80, targetPort: 5003 } ]
---
apiVersion: v1
kind: ConfigMap
metadata: { name: license-api-code, namespace: ott-platform }
data:
  app.py: |
    from flask import Flask, request, jsonify
    app = Flask(__name__)
    @app.get("/health")
    def h(): return ("ok",200)
    @app.get("/ready")
    def r(): return ("ok",200)
    @app.post("/license")
    def license_issue():
      b = request.get_json(force=True) or {}
      if not b.get("contentId") or not b.get("deviceId"):
        return jsonify(ok=False, error="missing fields"), 400
      # Stub DRM OK
      return jsonify(ok=True, licenseKey="ABC123-FAKE-KEY")
    if __name__=="__main__": app.run(host="0.0.0.0", port=5003)
