apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ott-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CodelyTV/ott-k8s-lab-v7.git
    targetRevision: main
    path: k8s/
  destination:
    server: https://kubernetes.default.svc
    namespace: ott-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
